### ISSUE TITLE
Disable players' preferences

### ISSUE THREAD

**Issue by Vitaly-Rudenko** [BenWoodworth/FastCraft#100]
Please, add an option to the config to disable creating empty <UUID>.yml files in preferences/ directory.

**Comment by BenWoodworth** [comment]
What's your concern with the empty preference files?

**Comment by MikroAcse** [comment]
Well, they don't do anything, but making backuping/copying server folder longer.
Also, it's little annoying in console.

**Comment by BenWoodworth** [comment]
I may change it in the future so all the preferences are stored in one file. I've been really busy with schoolwork recently, so I won't be able to get around to it for a while.

You can try adding something to your startup script that deletes all the empty files in the player preferences folder before the server starts up.

Thank you for the input!

**Comment by PhanaticD** [comment]
+1 all the empty files are totally unnecessary and cause backups to take longer

**Comment by CloudeLecaw** [comment]
+1 all the empty files are totally unnecessary and cause backups to take longer^^
