### ISSUE TITLE
PaperSpigot Duplication Glitch

### ISSUE THREAD

**Issue by TheWranger** [BenWoodworth/FastCraft#103]
## Description
Players are able to dupe items out of fastcraft. When a player clicks on an item in the FastCraft interface it gets sent to their inventory. Basically this means whenever somebody clicks the "Refresh" button, they get a nether star, or when somebody crafts something from the interface, they will receive double the amount they crafted.

## Debug Output
<pre><code>
========== FastCraft+ Debug Info ==========
Versions:
  FastCraft+ v0.26.4
  git-PaperSpigot-"8b18730" (MC: 1.8.8)
  1.8.8-R0.1-SNAPSHOT
  Java 1.8.0_101
Other Plugins (79):
  ActionAnnouncer 1.11.0
  AntiAD 2.8
  AntiAFKPlus 2.1
  AntiAura 10.89
  AuctionHouse 3.3
  BarAPI 3.1
  Beheaded 1.0
  BloodMoon 0.55-Samistine
  BookLimit 1.0-SNAPSHOT
  BurnGravel 1.0
  ChatControl 5.4.4
  ChatterBot 1.8.7
  ChestCommands 3.1.4
  ClearLag 2.9.3
  ColoredAnvils 1.08
  CombatTagPlus 1.2.3
  ConditionalCommands 1.2
  CratesPlus 4.4
  CSGO-CratesPlus 1.0
  CustomPayloadFixer 1.1
  CustomRain 0.0.1
  DeathMessagesPrime 1.11.16
  DragonSlayer 0.4.6_Jeppa
  DynamicMotd 1.2
  EasyBackup 2.2.0
  EnjinMinecraftPlugin 3.1.4
  EpicWorldGenerator 7.2.26
  Essentials 2.0.1-b469
  EssentialsChat 2.0.1-b469
  EssentialsSpawn 2.0.1-b469
  eZProtector 4.1.5
  Factions 1.6.9.5-U0.1.20
  FactionsHomes 1.0
  FastAsyncWorldEdit 17.04.21-59c2439-657-12.4.2
  FastPot 4.2
  FeatherBoard 3.18.1
  GAListener 1.3.1
  GUIShop 4.3
  HelpOP 1.1
  HolographicDisplays 2.2.5
  hungerFix 1.2
  InstantRespawn 1.0
  MelonCrack 1.5
  MineCordBot 2.0.2
  MineFriends 2.0
  Multiverse-Core 2.4-b527
  NoCheatPlus 3.15.2-SNAPSHOT-sMD5NET-b1087
  NoDroppingOffline 0.1
  ObsidianBreaker 2.0 Bug Fix
  PermissionsEx 1.23.4
  PetMaster 1.4.2
  PingVersion 1.0.0
  PlaceholderAPI 2.7.1
  PlayerMention 2.7
  PlugMan 2.1.1
  PNCP-ElfEdit 1.3-ElfEdit
  ProtocolLib 4.2.1
  Ram_Monitor 1
  RandomTeleport 5.11.0
  React 4.7p
  RecipeFinder 2.2
  RedstoneClockPreventer 1.3.1
  Shortr 1.02
  SilkSpawners 3.7.4
  Tablist 1.3.1.11
  TallNether 1.3.2
  UltimateTroll 1.5
  VanishNoPacket 3.20
  Vault 1.5.6-b49
  ViaVersion 1.0.4
  Votifier 2.3.4
  WhatIsIt 1.3.9
  WorldBorder 1.8.6
  WorldBorderPatches 2.0
  WorldEdit 6.1.5;4651611
  WorldEditSelectionVisualizer 1.4.5
  WorldGuard 6.1.3-SNAPSHOT;c904242
  WorldGuardExtraFlags 2.12.1
  XPboost 1.89
===========================================
</code></pre></details>

**Comment by BenWoodworth** [comment]
Do you think you would be able to post a video of this happening?

**Comment by TheWranger** [comment]
Was about to record then realised this is due to an issue with some other plugin.
Working to find out what's causing it...

**Comment by TheWranger** [comment]
Seems like I'm not getting it anymore.
I removed a few plugins that weren't working properly over the last couple of days so maybe it was one of those?
Or maybe the old .jar got corrupt or something like that.

**Comment by BenWoodworth** [comment]
Alright. It might be something you have to contact another plugin developer about.
