### ISSUE TITLE
Changes for 1.12 

### ISSUE THREAD

**Issue by CloudeLecaw** [BenWoodworth/FastCraft#106]
to be ready for 1.12 i updated the plugin to 1.12 recipes.
Problem "github said me i have to be "branches" to edit the langfile for de 🥉 

dont forget to rename the DE.yml.txt back to DE.yml ;)

[DE.yml.txt](https://github.com/BenWoodworth/FastCraft/files/1003749/DE.yml.txt)

**Comment by BenWoodworth** [comment]
I'll definitely have to make sure everything still works for 1.12. Thank you for the translation as well! 😄

**Comment by CloudeLecaw** [comment]
im currently useing it in the 1.12 pre5 i dont thing there will be so much plugincrushers anymore before the final release of 1.12 :)
but lets wait and see *g*
