### ISSUE TITLE
FastCraftPlus needs an update to 1.12 

### ISSUE THREAD

**Issue by Fonzee9** [BenWoodworth/FastCraft#107]
https://pastebin.com/v8KQ2Cic

**Comment by BenWoodworth** [comment]
Thanks for the heads up! It's currently finals week for me, so I'll have to wait a few days to work on this.

```
Caused by: java.lang.UnsupportedOperationException: Not supported in this Minecraft version.
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.hasAchievement(CraftPlayer.java:574) ~[craftbukkit.jar:git-Spigot-1ffab67-240f16d]
```

It looks like Player::hasAchievement() is no longer supported.
https://github.com/BenWoodworth/FastCraft/blob/v0.26.5/src/main/java/co/kepler/fastcraftplus/util/RecipeUtil.java#L76

**Comment by Fonzee9** [comment]
Would player.hasPlayedBefore work?

**Comment by Fonzee9** [comment]
:)

**Comment by BenWoodworth** [comment]
Achievements have prerequesites, so you can't get the **Getting Wood** ![Getting Wood](https://vignette3.wikia.nocookie.net/minecraft/images/8/8b/GettingWoodlogo.png/revision/latest?cb=20120531224933) achievement if you don't have the **Taking Inventory** ![Taking Inventory](https://vignette1.wikia.nocookie.net/minecraft/images/e/e4/TakingInventory.png/revision/latest/scale-to-width-down/45?cb=20160419132556) achievement.

![Achievements](https://vignette1.wikia.nocookie.net/minecraft/images/9/90/AchievementInterface.png/revision/latest?cb=20120226142531)

The if statement makes sure I'm only giving an achievement if the player has the previous achievements. I'm also pretty sure that the [code in the if statement](https://github.com/BenWoodworth/FastCraft/blob/v0.26.5/src/main/java/co/kepler/fastcraftplus/util/RecipeUtil.java#L77) will throw an error too.

**Comment by Fonzee9** [comment]
What if you removed that tiny code and just did player.hasPlayedBefore in the other one
