### ISSUE TITLE
Compatibility - Item Maker Pro

### ISSUE THREAD

**Issue by MianiteWorlds** [BenWoodworth/FastCraft#11]
Hi this plugin is amazing BUT there is a bug whit ItemMakerPro plugin, if you make perfect recapies whit the item maker plugin for example recipies whit custom items like a ingot named something makes a spasific sword. using fastcraft you able to craft the item using a regular ingot not a named one to create the sword ALso this plugin is amazing! Just please fix the bug
Thats the itemmaker plugin im talking about!
https://www.spigotmc.org/resources/item-maker-pro.7173/

**Comment by MianiteWorlds** [comment]
If you can let me know when this is fixed by posting on our servers enjin website or message me im new to this idk if it will send me a email notification the site MianiteWorlds.enjin.com
Thanks!

**Comment by BenWoodworth** [comment]
Thanks for reporting the issue. I'll let you know when it's resolved.

**Comment by MianiteWorlds** [comment]
i saw a new update came out, did it fix the bug? :)






`

**Comment by BenWoodworth** [comment]
Not yet. I'll let you know here

**Comment by BenWoodworth** [comment]
Can you try something for me?

If you create a recipe that has a custom named iron ingot as an ingredient, and make it craft into an iron block, what happens if you put a normal, unnamed iron ingot into the 3x3 crafting grid?

I can't do much testing because I don't have the plugin, and it costs money.

**Comment by MianiteWorlds** [comment]
it wouldn't make the iron block

**Comment by MianiteWorlds** [comment]
crafting made whit custom items (eg named ones)  only works when your using the named item to craft it not a regular un named one

**Comment by BenWoodworth** [comment]
Okay. Some other custom recipe plugins didn't create the recipes properly, and players could use regular items instead of the custom items to craft.

**Comment by MianiteWorlds** [comment]
Some dont have this, i worked personaly whit the ItemMaker dev to add that feature, i dont think he would allow me sending you a copy of the plugin, i would recommend going to the spigot page for the plugin and reading it hopefully this is solved soon :)

**Comment by BenWoodworth** [comment]
I'm working on adding my own custom recipe config for FastCraft+ now, so you'll be able to use that to register recipes with custom items.

**Comment by MianiteWorlds** [comment]
No.. please we didnt need that
we need it to show the ItemMaker recapies..

**Comment by MianiteWorlds** [comment]
We already have 500+ custom recipes on that
we wont move

**Comment by BenWoodworth** [comment]
It's a feature request I've gotten from several other users. I can contact the developer of ItemMakerPro about it.

**Comment by BenWoodworth** [comment]
He didn't want to share how his plugin managed recipes with metadata, so I might not be able to add full compatibility with his plugin.

If you'd like, you can share your Item Maker Pro recipes config with me, and I can add a feature to FastCraft+ that imports recipes.

**Comment by MianiteWorlds** [comment]
So it wont be fixed i guess? aww well thanks for trying, maybe you can make a 'craft book plugin' that opens a gui on right click and shows all the normal and custom crafting from other plugins and and add support for the custom crafting from ItemMaker?

**Comment by BenWoodworth** [comment]
He's going to show me the api later, so we'll see.

**Comment by MianiteWorlds** [comment]
any updates

**Comment by BenWoodworth** [comment]
He gave me access to his plugin, but I haven't started with compatibility
yet.

**Comment by BenWoodworth** [comment]
I just released v0.5, which has compatibility for Item Maker Pro added. Can you test it to see how it works?

**Comment by MianiteWorlds** [comment]
it doesnt work, when i open a crafting table it says crafting failed and says a title message crafting failed and doesnt show the custom item in the gui

**Comment by BenWoodworth** [comment]
Can you test it out with v0.11?

**Comment by MianiteWorlds** [comment]
Ill get right on that once i upload my new video

**Comment by MianiteWorlds** [comment]
Tested whit the latest version it does not show any custom recipes in the gui

**Comment by MianiteWorlds** [comment]
when you have the required items in your inventory

**Comment by MianiteWorlds** [comment]
Hello haven't herd for you hows it going on the fix

**Comment by BenWoodworth** [comment]
Sorry, I've been pretty busy with schoolwork. I was planning on testing for incompatibility with plugins later if I have time.

**Comment by BenWoodworth** [comment]
The Item Maker Pro dev obfuscated his code, and it wound up breaking his API. I have to wait until he fixes the issue to continue fixing compatibility.

**Comment by BenWoodworth** [comment]
Are there still any incompatibilities with Item Maker Pro?

**Comment by MianiteWorlds** [comment]
before you wore able to craft 'perfect recipes' but whit all items not the spastic named ones
now your not able to craft perfect recipes at all whit any items..

**Comment by BenWoodworth** [comment]
Closed because the resource is no longer posted on spigotmc
