### ISSUE TITLE
Custom Recipes from other plugins broken.

### ISSUE THREAD

**Issue by BurntValentine** [BenWoodworth/FastCraft#111]
## Description
A couple of plugins we use add custom recipes for their items (and can't be moved to FCs recipes file as a result to work around this) but if you open the FastCraft menu with the items to craft those plugins items in your inventory you get a big error in the console, and it doesn't show any recipes at all (not just those for the plugin items) that it should be showing.
Both plugins items work perfectly fine without FastCraft being installed.

## Reproduction
*mostly explained above*

## Output/Files
Console error: https://pastebin.com/JLqAiheX

## Server Details
- FastCraft Version: 
0.27.1
- Server Version: 
Spigot 1.12 (latest)
- Relevant Plugins: 
EasyElevators: https://www.spigotmc.org/resources/easy-elevators.18733/
SafariNets: https://www.spigotmc.org/resources/safarinet-capture-mobs.9732/

**Comment by BenWoodworth** [comment]
Thanks for the report. This'll be fixed in v0.27.2
