### ISSUE TITLE
Prefixes, names

### ISSUE THREAD

**Issue by Someone-NEW** [BenWoodworth/FastCraft#117]
I suggest you to add a configurable names so we can change names like "FastCraft+" everywhere to something custom names or server names etc. when you see on chat or open GUI to see some cool names or animated names whatever just put this to be possible to change tnx

**Comment by BenWoodworth** [comment]
You can change the GUI's title using the language files. And unfortunately, it's not possible to animate the GUI title, since the title cannot be changed once the inventory is created.
