### ISSUE TITLE
Compatibility issues with older MC Versions

### ISSUE THREAD

**Issue by CloudeLecaw** [BenWoodworth/FastCraft#118]
Jep u heared right, Your config design is creation errros on older Spigot Version (lower then 1.9.x - so all 1.8.x and the firsts 1.9.x Versions)

read this Spigot post here
https://www.spigotmc.org/threads/fastcraft.133803/page-34#post-2702869
on this page a user had this problem, first i didnt understand what he wanted, or why he was posting this. then i tested it with different Spigot Versions, so see how long this error of wong config converstion exists. i crated on the spigotsite a little fix for him. For this i replaced your whole config.yml if a working one in the jarfile. i was suppriced that all "#infos" from my config got removed on creation, but ok this may is how config files are created in 1.8.... 
But ok, even if the # Infos are not inside the created config.yml, this "new" config.yml works for the old Spigot versions.

So may u have an idea for further updated to rethink about the creation of config.yml? <3
by the way - Fastcraft+ is this the best plugin X-D

**Comment by BenWoodworth** [comment]
Thanks for looking into it for me!

This has been an issue for a few people, but I've never figured out it was the version of spigot.

I'll work on a fix when I get around to it. I've been really busy with schoolwork, job searching, and a hand injury. I'll be thinking of a good solution in the meantime :)
