### ISSUE TITLE
Invisible world issue when adding Fastcraft to presumably stable 1.7.10 modpack

### ISSUE THREAD

**Issue by Trisscar05** [BenWoodworth/FastCraft#121]
Grabbed an old 1.7.10 pack to test out EE3, never having got the chance to, and after a bunch of messing around to get things to stop crashing and updated, pack loaded just fine albeit with medial lag and FPS issues. World loaded fine afaik and I messed with settings so they weren't set to extreme everything.
Went to add fastcraft, and upon reload of the already genned world the blocks were invisible, the only things I could see were floating animals and the sky/void skybox, along with the selection border of anything I was close enough to mouse over. Restarts of the world, the game, and my computer, as well as changing allocated RAM from 4 to 6 hasn't had any noticeable effect, and leaving it alone for a while doesn't make the blocks suddenly appear like it usually does if loading is being silly.
Console doesn't seem to have much that's relevant (adding the pastebin link below) beyond a good chunk of spam in the form of "FastCraft: rg lookup failed".
https://pastebin.com/YiyDBAeF
(If something's missing from it, that's because I set Twitch/Curse to use the native launcher, which meant I had to go in and copy everything by hand. Lemme know if I need to go do that again or find another way of grabbing it that doesn't omit things, or if I should try the jar launcher instead.)
Computer specs are;
Win7, 64bit
16gb RAM
AMD A4-5300 APU 3.40GHz
AMD Radeon HD 7800 graphics card
Drivers were updated about a month ago, and I've being playing Sky Factory 3 for a while just previous to this, so definitely capable of running it.

**Comment by BenWoodworth** [comment]
Hi. You (understandibly) confused this server plugin, FastCraft, for a mod that took the same name.
Try messaging [Player](https://forum.industrial-craft.net/core/user/50/) (the developer of the mod), or making a comment in his forum post:
https://forum.industrial-craft.net/thread/10820/

Best of luck!

**Comment by Trisscar05** [comment]
Ooooh, crap I'm sorry.
Just typed fastcraft github in google, crap. Sincere apologies, and thanks. XD

**Comment by BenWoodworth** [comment]
No worries lmao
You're definitely not the first.
