### ISSUE TITLE
Compatibility - ProRecipes (Tripwire Hooks)

### ISSUE THREAD

**Issue by Feeriix** [BenWoodworth/FastCraft#13]
Plugin page: https://www.spigotmc.org/resources/1-7-1-9-prorecipes-best-recipe-manager-no-configs-now-with-4x4-multi-crafting.9039/
Developer API: https://www.spigotmc.org/wiki/prorecipes-recipeapi/

**Comment by BenWoodworth** [comment]
I just released v0.5, which has compatibility support for ProRecipes. I'm unable to test it, as I haven't purchased the plugin, so could you test the compatibility, and report back?

**Comment by Feeriix** [comment]
http://i.imgur.com/480lXmY.png
"Crafting" it will give you the tripwire hook and take the crafting items.
But the recipe is correct, just need the name and correct result.

**Comment by Feeriix** [comment]
NPE with v0.11
http://pastebin.com/SEt1CA4s
http://i.imgur.com/4p9OhVB.png

**Comment by BenWoodworth** [comment]
Can you give this a try?
[FastCraftPlus.zip](https://github.com/BenWoodworth/FastCraftPlus/files/205005/FastCraftPlus.zip)

**Comment by Feeriix** [comment]
Now I can see the custom items, but not their custom names.
Console spam: [FastCraftPlus] Can't find item name: ItemStack{AIR x 0}
http://i.imgur.com/ck5JOA8.png
Other than that, it seems to be working perfectly. Good work!

**Comment by Feeriix** [comment]
On some recipes, the tripwire hook is there.
http://i.imgur.com/LgMwG9T.png

**Comment by BenWoodworth** [comment]
The spam messages are disabled in this jar:
[FastCraftPlus.zip](https://github.com/BenWoodworth/FastCraftPlus/files/205184/FastCraftPlus.zip)

Is the tripwire hook a custom recipe? Or does that also happen without ProRecipes?

**Comment by Feeriix** [comment]
Thanks. The hooks are shadow copies of the custom items with the same ingredient requirements.
Tested without ProRecipes, and they don't show up.

**Comment by BenWoodworth** [comment]
Okay. I think I have an idea what is happening. I'll give you another jar
to test when I have some free time later, or maybe tomorrow.

**Comment by BenWoodworth** [comment]
I just released v0.12. I'm not sure if it solved the problem, but please give it a try.

**Comment by Feeriix** [comment]
Names are shown correctly but the tripwire hooks are still there.
http://i.imgur.com/8rPhgQM.png
Only shaped recipes are affected.

**Comment by BenWoodworth** [comment]
This jar will print out a debug message in the console when ProRecipes items show up in the UI. Can you show me the output when the duplicate hooks are showing up?
[FastCraftPlus.zip](https://github.com/BenWoodworth/FastCraftPlus/files/207709/FastCraftPlus.zip)

**Comment by Feeriix** [comment]
http://pastebin.com/CHVNSgrQ
Could it be a config issue perhaps?

**Comment by BenWoodworth** [comment]
I think I'm seeing the problem. The hook recipes aren't recipes you registered, but for every recipe you create, a hook recipe is also created with the same ingredients. I'm going to contact the dev about it to figure out exactly what's happening, and how to fix it.

**Comment by BenWoodworth** [comment]
Are you able to craft the tripwire hooks when you click on them?

**Comment by Feeriix** [comment]
Yes

**Comment by BenWoodworth** [comment]
The dev of ProRecipes is going to be adding something to the API that will let me hide the tripwire hooks. I'll let you know when I implement the fix.

**Comment by Feeriix** [comment]
Any news on this?

**Comment by BenWoodworth** [comment]
The developer has been busy with other things
![screenshot_2016-05-24-15-54-16](https://cloud.githubusercontent.com/assets/1829157/15517920/5998190a-21c8-11e6-9c56-efe7a1dccd1a.png)

You can try adding tripwire hooks to the blacklist config for now.

**Comment by Feeriix** [comment]
Still seeing hook recipes with ProRecipes on v0.26.3. 
https://snag.gy/bIkhce.jpg

**Comment by BenWoodworth** [comment]
I forgot about this issue, sorry about that.
I don't believe Drepic has gotten around to improving the API. I will contact him about it.
For now, I think your best bet is still to blacklist the hooks.

**Comment by Feeriix** [comment]
I added these values and it still shows up, am I doing something wrong?

results:
- ['minecraft:tripwire_hook']
- ['minecraft:tripwire_hook', 'ANY', '{display:{Name:"recipedshapeditem"}}']

**Comment by Feeriix** [comment]
Now that the plugin is open source, is there an easy fix?

**Comment by BenWoodworth** [comment]
Sorry that I didn't respond. I believe this should work:
```
results:
  tripwire hooks: ['minecraft:tripwire_hook']
  ProRecipes shaped: ['minecraft:tripwire_hook', 'ANY', '{display:{Name:"recipedshapeditem"}}']
```

I started working on re-writing FastCraft because there were some fundamental issues with handling recipes from other plugins. I'm changing how it handles recipes so recipes from other plugins are handled the same way they would be if they were crafted in a crafting table by the player. I can't say when I'll finally be able to release the changes, since I've been really busy with schoolwork, but I will make sure that it handles recipes from ProRecipes correctly.

**Comment by BenWoodworth** [comment]
Should be fixed in the latest release
