### ISSUE TITLE
Server hangs on shutdown

### ISSUE THREAD

**Issue by Sodies** [BenWoodworth/FastCraft#133]
# Temporary Fix
I ([Ben](https://github.com/BenWoodworth/)) created a temporary fix on the [v2/crashfix](https://github.com/BenWoodworth/FastCraft/tree/v2/crashfix) branch. It removes the code that closes GUIs when the plugin disabled (which is where the issue lies), so **the `/reload` command should not be used with this build.** If it is, the GUI inventory won't be closed, and players will be able to take items from it.

Here's the latest [v2/crashfix](https://github.com/BenWoodworth/FastCraft/tree/v2/crashfix) build (based on v2.0.2): [FastCraft-2.x-18919b2.jar](https://github.com/BenWoodworth/FastCraft/files/4248276/FastCraft-2.x-18919b2.zip)
I'm not actively updating this, so let me know you'd like me to. 😄
\- Ben

# Issue
## Description
Sometimes server crash

## Reproduction
- Install Plugin
- Play
- ...

## Output/Files
```
09.01 16:29:19 [Server] ERROR The server has stopped responding!
09.01 16:29:19 [Server] ERROR Please report this to http://www.spigotmc.org/
09.01 16:29:19 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
09.01 16:29:19 [Server] ERROR Spigot version: git-Spigot-549c1fa-8c37e2e (MC: 1.12.2)
09.01 16:29:19 [Server] ERROR ------------------------------
09.01 16:29:19 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!):
09.01 16:29:19 [Server] ERROR ------------------------------
09.01 16:29:19 [Server] ERROR Current Thread: Server thread
09.01 16:29:19 [Server] ERROR PID: 38 | Suspended: false | Native: false | State: RUNNABLE
09.01 16:29:19 [Server] ERROR Stack:
09.01 16:29:19 [Server] ERROR java.lang.System.identityHashCode(Native Method)
09.01 16:29:19 [Server] ERROR com.google.common.base.Equivalence$Identity.doHash(Equivalence.java:372)
09.01 16:29:19 [Server] ERROR com.google.common.base.Equivalence.hash(Equivalence.java:117)
09.01 16:29:19 [Server] ERROR com.google.common.collect.MapMakerInternalMap.hash(MapMakerInternalMap.java:908)
09.01 16:29:19 [Server] ERROR com.google.common.collect.MapMakerInternalMap.get(MapMakerInternalMap.java:2123)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector.getMarker(ChannelInjector.java:746)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1138)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:929)
09.01 16:29:19 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:404)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.api.gui.GUI.dispose(GUI.java:107)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.api.gui.GUI.dispose(GUI.java:96)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.craftgui.GUIFastCraft.dispose(GUIFastCraft.java:84)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.craftgui.GUIFastCraft$GUIListener.blockRemoved(GUIFastCraft.java:220)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.craftgui.GUIFastCraft$GUIListener.onBlockBreak(GUIFastCraft.java:199)
09.01 16:29:19 [Server] ERROR sun.reflect.GeneratedMethodAccessor392.invoke(Unknown Source)
09.01 16:29:19 [Server] ERROR sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09.01 16:29:19 [Server] ERROR java.lang.reflect.Method.invoke(Method.java:498)
09.01 16:29:19 [Server] ERROR org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
09.01 16:29:19 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
09.01 16:29:19 [Server] ERROR org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
09.01 16:29:19 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
09.01 16:29:19 [Server] ERROR java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
09.01 16:29:19 [Server] ERROR java.util.concurrent.FutureTask.run(FutureTask.java:266)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
```

## Server Details
- FastCraft Version: 2.0.2
- 1.12.2 spigot

**Comment by BenWoodworth** [comment]
It looks you're missing a few lines of the beginning of the error. Could you share the whole thing?

Also, are you using protocol lib? And what version?

**Comment by Sodies** [comment]
09.01 16:29:19 [Server] ERROR The server has stopped responding!
09.01 16:29:19 [Server] ERROR Please report this to http://www.spigotmc.org/
09.01 16:29:19 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
09.01 16:29:19 [Server] ERROR Spigot version: git-Spigot-549c1fa-8c37e2e (MC: 1.12.2)
09.01 16:29:19 [Server] ERROR ------------------------------
09.01 16:29:19 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!):
09.01 16:29:19 [Server] ERROR ------------------------------
09.01 16:29:19 [Server] ERROR Current Thread: Server thread
09.01 16:29:19 [Server] ERROR PID: 38 | Suspended: false | Native: false | State: RUNNABLE
09.01 16:29:19 [Server] ERROR Stack:
09.01 16:29:19 [Server] ERROR java.lang.System.identityHashCode(Native Method)
09.01 16:29:19 [Server] ERROR com.google.common.base.Equivalence$Identity.doHash(Equivalence.java:372)
09.01 16:29:19 [Server] ERROR com.google.common.base.Equivalence.hash(Equivalence.java:117)
09.01 16:29:19 [Server] ERROR com.google.common.collect.MapMakerInternalMap.hash(MapMakerInternalMap.java:908)
09.01 16:29:19 [Server] ERROR com.google.common.collect.MapMakerInternalMap.get(MapMakerInternalMap.java:2123)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector.getMarker(ChannelInjector.java:746)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
09.01 16:29:19 [Server] ERROR com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1138)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:929)
09.01 16:29:19 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:404)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.api.gui.GUI.dispose(GUI.java:107)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.api.gui.GUI.dispose(GUI.java:96)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.craftgui.GUIFastCraft.dispose(GUIFastCraft.java:84)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.craftgui.GUIFastCraft$GUIListener.blockRemoved(GUIFastCraft.java:220)
09.01 16:29:19 [Server] ERROR co.kepler.fastcraft.craftgui.GUIFastCraft$GUIListener.onBlockBreak(GUIFastCraft.java:199)
09.01 16:29:19 [Server] ERROR sun.reflect.GeneratedMethodAccessor392.invoke(Unknown Source)
09.01 16:29:19 [Server] ERROR sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09.01 16:29:19 [Server] ERROR java.lang.reflect.Method.invoke(Method.java:498)
09.01 16:29:19 [Server] ERROR org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
09.01 16:29:19 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
09.01 16:29:19 [Server] ERROR org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
09.01 16:29:19 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
09.01 16:29:19 [Server] ERROR java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
09.01 16:29:19 [Server] ERROR java.util.concurrent.FutureTask.run(FutureTask.java:266)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
09.01 16:29:19 [Server] ERROR net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)

**Comment by BenWoodworth** [comment]
Are you running ProtocolLib? And if you are, can you see if this is an issue without it?

**Comment by BenWoodworth** [comment]
Source:

<details>
<summary>java.lang.System.identityHashCode(Native Method)</summary>
<pre>
(Native Method)
</pre>
</details>

<details>
<summary>com.google.common.base.Equivalence$Identity.doHash(Equivalence.java:372)</summary>
<pre>
    protected int doHash(Object o)
    {
      return System.identityHashCode(o); // <-----
    }
</pre>
</details>

<details>
<summary>com.google.common.base.Equivalence.hash(Equivalence.java:117)</summary>
<pre>
  public final int hash(@Nullable T t)
  {
    if (t == null) {
      return 0;
    }
    return doHash(t); // <-----
  }
</pre>
</details>

<details>
<summary>com.google.common.collect.MapMakerInternalMap.hash(MapMakerInternalMap.java:908)</summary>
<pre>
  int hash(Object key)
  {
    int h = this.keyEquivalence.hash(key);
    return rehash(h); // <-----
  }
</pre>
</details>
<br/>TODO:
<details>
<summary>com.google.common.collect.MapMakerInternalMap.get(MapMakerInternalMap.java:2123)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>com.comphenix.protocol.injector.netty.ChannelInjector.getMarker(ChannelInjector.java:746)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1138)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:929)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:404)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>co.kepler.fastcraft.api.gui.GUI.dispose(GUI.java:107)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>co.kepler.fastcraft.api.gui.GUI.dispose(GUI.java:96)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>co.kepler.fastcraft.craftgui.GUIFastCraft.dispose(GUIFastCraft.java:84)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>co.kepler.fastcraft.craftgui.GUIFastCraft$GUIListener.blockRemoved(GUIFastCraft.java:220)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>co.kepler.fastcraft.craftgui.GUIFastCraft$GUIListener.onBlockBreak(GUIFastCraft.java:199)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>sun.reflect.GeneratedMethodAccessor392.invoke(Unknown Source)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>java.lang.reflect.Method.invoke(Method.java:498)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:889)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>java.util.concurrent.FutureTask.run(FutureTask.java:266)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)</summary>
<pre>
TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)</summary>

TODO
</pre>
</details>

<details>
<summary>net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)</summary>
<pre>
TODO
</pre>
</details>

**Comment by BenWoodworth** [comment]
This seems like an issue with `Map`s using `System.identityHashCode`. I'm not entirely sure what's causing it, but I don't think it's an issue with FastCraft.

Here are some similar crashes I found with the same problem:
https://pastebin.com/raw/gMGzUSeq
https://www.spigotmc.org/threads/my-server-is-crashing.193057/
https://github.com/CanaryModTeam/CanaryMod/issues/119
http://www.minecraftforum.net/forums/support/server-support/2214427-server-is-constanly-crashing

**Comment by BenWoodworth** [comment]
I'm wondering if it might be an issue with your server not having enough memory allocated. Do you know how much it's using?

e.g:

    java -jar Server.jar -Xms512m -Xmx1024m
                             ^^^^     ^^^^^

**Comment by BenWoodworth** [comment]
https://www.spigotmc.org/threads/fastcraft.133803/page-37#post-2916604
>**Sckaletz:**
> The latest update seems to crash my server all the time. 
> Using latest release of Spigot 1.12.2.
> https://pastebin.com/amwWhCfN

**Comment by kakd** [comment]
I had this same issue on my server. This is a really nice plug-in but unfortunately, I had to uninstall Fastcraft after this. Hopefully, sharing my server details will help you figure out what's causing this so you can fix it. This started happening to my server with an older 1.x versions, so I updated the plug-in to the newest 2.0.3 version and the problem continued, at which pointso I can't remember which plugins are new, but when I uninstalled Fastcraft, my plugins were: CoreProtect, LuckPerms, NPC-Inventory, OpenInv, ClearLag, PlugMan, NoSpawnerChange, PingPlayer, Votifier, Multiverse-Core, VotingPlugin, FastAsyncWorldEdit, iDisguise, Multiverse-Inventories, ViaVersion, Vault, ViaBackwards, SimpleSit, WorldEdit, Essentials, Minigames, LWC, WorldGuard, DiscordSRV, EssentialsChat, EssentialsAntiBuild, ServerSigns, GriefPrevention, EssentialsSpawn, EnjinMinecraftPlugin, WorldGuardExtraFlags, RandomCoords, ChestShop, BKCommonLib, LightCleaner, HorseTpWithMe, and Fastcraft.

**Comment by BenWoodworth** [comment]
Is this still an issue with the latest v3.0 alpha build? ([here](https://github.com/BenWoodworth/FastCraft/releases), for Bukkit 1.14+)
