### ISSUE TITLE
Startup Error {PRIORITY: MEDIUM}

### ISSUE THREAD

**Issue by GameHoundInteractive** [BenWoodworth/FastCraft#135]
## Description
Error upon startup, It seems to have no effect but id like it gone.

## Output/Files
- Stack Trace: https://hastebin.com/higeqosare.md
- `/fcadmin debug`: https://hastebin.com/ojoqiwusew.md
- RELEVANT CONFIGS: https://hastebin.com/memazuzici.php

## Server Details
- FastCraft Version: 2.0.2
- Server Version: BUKKIT/SPIGOT/SPONGE 1.8.8 paper

**Comment by BenWoodworth** [comment]
This has happened for a couple other people before, and I'm not specifically sure what's causing the config to be created incorrectly.

Give this a shot, and see if it fixes the problem:
https://github.com/BenWoodworth/FastCraft/wiki/Startup-Error-Fix:-expected-'-document-start-'

**Comment by GameHoundInteractive** [comment]
Fixed, But ur wiki post, fix it, It says to change back to zip not jar :P
