### ISSUE TITLE
stopmergexxxx?

### ISSUE THREAD

**Issue by CloudeLecaw** [BenWoodworth/FastCraft#138]
Sometimes when to much items spawns FastCraft creates or assa a purel lore to an item,
Problem is u cant stack this item anymore because fo this custom lore.
![image](https://user-images.githubusercontent.com/12080017/38048534-ef349708-32c5-11e8-85d5-014ea3086e38.png)
It took me a while to find out that its FastCraft that is causing this.

**Comment by BenWoodworth** [comment]
This looks like it's caused by issue #84

**Comment by CloudeLecaw** [comment]
sorry for Posting here i was a Plugin called AntiDropeMerge i thought first it was fastcraft because it was stoping first when i unloaded fastcraft but now i saw that ist this Plugin called AntiDropeMerge… so this was a failaure created isses from me (and also the reason why i closed it :3
