### ISSUE TITLE
1.13 Support?

### ISSUE THREAD

**Issue by TheCompieter** [BenWoodworth/FastCraft#142]
it's not working in 1.13

21:59:15 [WARNING] Dev > java.lang.IllegalArgumentException: ordinal on modern Material
21:59:15 [WARNING] Dev > at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
21:59:15 [WARNING] Dev > at org.bukkit.craftbukkit.v1_13_R1.util.CraftLegacy.ordinal(CraftLegacy.java:218)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.recipes.FastRecipe.getByproducts(FastRecipe.java:136)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.recipes.FastRecipe.hashCode(FastRecipe.java:280)
21:59:15 [WARNING] Dev > at java.util.HashMap.hash(HashMap.java:339)
21:59:15 [WARNING] Dev > at java.util.HashMap.put(HashMap.java:612)
21:59:15 [WARNING] Dev > at java.util.HashSet.add(HashSet.java:220)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.compat.Compat_Bukkit.getRecipes(Compat_Bukkit.java:51)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.compat.RecipeCompatManager.getRecipes(RecipeCompatManager.java:73)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.craftgui.layouts.LayoutRecipesItems.<init>(LayoutRecipesItems.java:21)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.craftgui.LayoutManager.getNewLayout(LayoutManager.java:26)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.craftgui.GUIFastCraft.<init>(GUIFastCraft.java:51)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.commands.CmdCraft.open(CmdCraft.java:52)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.commands.CmdCraft.onCommand(CmdCraft.java:33)
21:59:15 [WARNING] Dev > at co.kepler.fastcraft.commands.CommandManager.onCommand(CommandManager.java:46)
21:59:15 [WARNING] Dev > at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
21:59:15 [WARNING] Dev > at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
21:59:15 [WARNING] Dev > at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10)
21:59:15 [WARNING] Dev > at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
21:59:15 [WARNING] Dev > at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
21:59:15 [WARNING] Dev > at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
21:59:15 [WARNING] Dev > at java.lang.Thread.run(Thread.java:748)

**Comment by BenWoodworth** [comment]
FastCraft v3.0 will support Minecraft 1.13 when it is released. It's hard to say when I'll be able to release it, since I'll be busy with school, and I've been having medical issues with my hands that make it hard to code. I'm guessing it'll be at least another couple months, but I can't really be sure.

You can take a look at this to see the v3.0 progress:
https://github.com/BenWoodworth/FastCraft/projects/4

I hope this helps 😃

**Comment by TheCompieter** [comment]
thanks i hope you wil get better soon
