### ISSUE TITLE
Server thread dump crash

### ISSUE THREAD

**Issue by justinbea** [BenWoodworth/FastCraft#144]
## Description
DESCRIBE ISSUE
SERVER CRASH WHILE TRYING TO CRAFT SOMETHING

## Reproduction
- STEP 1
- STEP 2
- ...
crafting something with the gui

## Output/Files
- Stack Trace: https://gist.github.com/
- `/fcadmin debug`: https://gist.github.com/      https://pastebin.com/DUAar6Dd
- RELEVANT CONFIGS: https://gist.github.com/     https://pastebin.com/Wfs4gVJL

ERROR IN CONSOLE https://pastebin.com/ZzFaEKZg

## Server Details
- FastCraft Version: 2.0.3
- Server Version: BUKKIT/SPIGOT/SPONGE 1.12.2
- RELEVANT PLUGINS: https://pastebin.com/DUAar6Dd

**Comment by BenWoodworth** [comment]
This looks like the same issue as https://github.com/BenWoodworth/FastCraft/issues/133
Could you try the "temporary fix" at the top of that issue?

**Comment by justinbea** [comment]
thread closed
