### ISSUE TITLE
Custom Items and Textures compatibility

### ISSUE THREAD

**Issue by VenesArt** [BenWoodworth/FastCraft#145]
Hello,
I wanted to ask about compatibility patch to this plugin (https://dev.bukkit.org/projects/custom-items-and-textures). Would be great to have it!

Server Details
- FastCraft Version: 2.0.3
- Server Version: SPIGOT 1.12.2
- RELEVANT PLUGINS: Custom Items 1.12 3.2

**Comment by BenWoodworth** [comment]
Hi! What about that plugin isn't compatible with FastCraft?

**Comment by VenesArt** [comment]
Basically, custom recipes from that plugins aren't showing in FastCraft crafting menu.

**Comment by BenWoodworth** [comment]
This looks like something I'll be able to add. I'll try to add it in FastCraft v3.0.

**Comment by BenWoodworth** [comment]
Could you test compatibility with [the latest release](https://github.com/BenWoodworth/FastCraft/releases)?
