### ISSUE TITLE
Build Server Error

### ISSUE THREAD

**Issue by Diamondman121314** [BenWoodworth/FastCraft#146]
I'm not sure if this would be the right place to report this, but it seems as downloading from your build server isn't working. This goes for trying to download any build from there.
![image](https://user-images.githubusercontent.com/22570455/58674967-3604ff00-8320-11e9-97b0-3064e9eb632a.png)

**Comment by BenWoodworth** [comment]
Thanks for reporting! I had no idea...
It looks like `+` isn't being escaped in the links' URL's.

For now you can replace `+` with `%2B` in the URL to get the right download link:
[https://s3.amazonaws.com/fastcraft/circleci/357/fastcraft-3.0.0-unknown%2Butc.20190521182502.jar]()

**Comment by BenWoodworth** [comment]
Should be fixed now :)

**Comment by Diamondman121314** [comment]
Thank you!
