### ISSUE TITLE
plugin working only for OPs

### ISSUE THREAD

**Issue by MarBar-SK** [BenWoodworth/FastCraft#147]
## Description
Plugin works only for opped players. Yes I tried toggling it on for specific player but nothing seems to work only if I op player, than it works... Server doesn´t have any permissions plugin...

## Server Details
- FastCraft Version: 2.0.3
- Server Version: Spigot 1.8.8 (lightningmc.dlinkddns.com)
- Raspberry pi 3B+

**Comment by BenWoodworth** [comment]
Hello! You can use your server's permissions.yml file to configure permissions for your players. You can find an example here:
https://github.com/BenWoodworth/FastCraft/wiki/Permissions#sample-permissionsyml
