### ISSUE TITLE
FastCraft v3 Alpha

### ISSUE THREAD

**Issue by BenWoodworth** [BenWoodworth/FastCraft#148]
Discussion for the v3 alpha builds. Report any issues related to the alpha builds here.

The alpha builds can be downloaded on the [releases page](https://github.com/BenWoodworth/FastCraft/releases).

## Things to test for
- Bugs with the features listed in the release descriptions
- Incorrectly crafted items
- Crafting items without having all the ingredients
- Item duplication bugs
- Compatibility with other plugins ([issues](https://github.com/BenWoodworth/FastCraft/labels/compatibility))
- Compatibility with different server software/versions

## Known issues
- [ ] Recipes are shown even if they can't be crafted anymore
- [ ] Newly craftable recipes aren't shown when new items are added to inventory
- [x] Opening and clicking the UI is laggy the first time
    - Seems to be an issue with CraftBukkit: [SPIGOT-5534](https://hub.spigotmc.org/jira/browse/SPIGOT-5534)

**Comment by SlimeDog** [comment]
plugins/FastCraft/ and contents are not created on clean install.

**Comment by SlimeDog** [comment]
Please do not open the FC inventory menu on player connect. Or make it a configurable option.

**Comment by SlimeDog** [comment]
Do you want things recorded here, or as separate issues?

**Comment by BenWoodworth** [comment]
Reporting things here is fine. There's probably a lot of small things to report, so it doesn't really make sense to open a bunch of issues.

I haven't implemented configuration yet, so there's no need for a /plugins/FastCraft folder yet.

And I also haven't implemented opening FastCraft by clicking a crafting table yet, so I open it on player join for now. It'll only be like that for the alpha builds until you can open through a crafting table.

**Comment by SlimeDog** [comment]
OK. Is there a command to open the FC crafting table?

**Comment by BenWoodworth** [comment]
Not yet. Pretty much the only features added so far are the ones listed in
the release

**Comment by SlimeDog** [comment]
Please prioritize implementing the methods to open the menu. Reconnect is not a pretty alternative.

**Comment by BenWoodworth** [comment]
### [FastCraft v3.0.0-alpha.1](https://github.com/BenWoodworth/FastCraft/releases/tag/v3.0.0-alpha.1)

**Comment by SlimeDog** [comment]
Confirmed in 3.0.3-alpha.1:
- Disable opening FastCraft GUI on join
- Open FastCraft GUI when opening a crafting table
- Open **vanilla** crafting grid when the crafting table button is pressed (was this the intent?)

**Comment by BenWoodworth** [comment]
I'm not sure what you mean with the vanilla crafting table. When you're in the FastCraft UI, left clicking the crafting table button should open the vanilla crafting grid. I'm not sure what you mean by pressing (**E**) though

**Comment by SlimeDog** [comment]
Maybe I don't understand what is the "crafting table button". Please explain.

**E** opens the inventory, as expected. Is the crafting table button there?

**Comment by BenWoodworth** [comment]
This is the button I'm talking about, on the top right:
![image](https://user-images.githubusercontent.com/1829157/72852031-5866d680-3c7b-11ea-84bb-77859272889a.png)

Clicking it should open up the vanilla 3x3 crafting grid.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by BenWoodworth** [comment]
### [FastCraft v3.0.0-alpha.2](https://github.com/BenWoodworth/FastCraft/releases/tag/v3.0.0-alpha.2)

**Comment by BenWoodworth** [comment]
### [FastCraft v3.0.0-alpha.3](https://github.com/BenWoodworth/FastCraft/releases/tag/v3.0.0-alpha.3)

**Comment by BenWoodworth** [comment]
### [FastCraft v3.0.0-alpha.4](https://github.com/BenWoodworth/FastCraft/releases/tag/v3.0.0-alpha.4)

**Comment by BenWoodworth** [comment]
### [FastCraft v3.0.0-alpha.5](https://github.com/BenWoodworth/FastCraft/releases/tag/v3.0.0-alpha.5)

**Comment by BenWoodworth** [comment]
### [FastCraft v3.0.0-alpha.6](https://github.com/BenWoodworth/FastCraft/releases/tag/v3.0.0-alpha.6)

**Comment by BenWoodworth** [comment]
I've released [FastCraft v3.0.0-beta](https://github.com/BenWoodworth/FastCraft/releases/tag/v3.0.0-beta)! If you find any issues, you can make an issue for it instead of posting here :)
