### ISSUE TITLE
v3 Compatibility - Protocol Support

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [BenWoodworth/FastCraft#149]
## Description
When joining with an older client version you get weird crafting recipes
![image](https://user-images.githubusercontent.com/27149563/74685449-e678a300-51ce-11ea-8cca-5b200a66b283.png)
![image](https://user-images.githubusercontent.com/27149563/74685470-f6908280-51ce-11ea-91e3-6458e675349a.png)
It thinks it can craft stone stairs with end crystals because they are stone blocks on the client side

## Reproduction
- Install FastCraft with ProtoclSupport (and maybe ProtocolSupportStuff, to see what the recipe would produce in newer version)
- Join with older version
- Enjoy broken recipes

## Output/Files
- Stack Trace: N/A
- `/fcadmin debug`: Command not existing
- RELEVANT CONFIGS: FastCraft and ProtocolSupport have no configs

## Server Details
- FastCraft Version: 3.0.0-alpha.4
- Server Version: Paper-243 for 1.14.4
- RELEVANT PLUGINS: ProtocolSupport

**Comment by BenWoodworth** [comment]
I wasn't able to reproduce this. I'm only seeing one Stonecutter recipe, and it looks fine for me.
- Client: Minecraft 1.13.2
- Server: [Paper-243 for 1.14](https://papermc.io/ci/job/Paper-1.14/243/)
- [FastCraft 3.0.0-alpha.4](https://github.com/BenWoodworth/FastCraft/releases/tag/v3.0.0-alpha.4)
- [ProtocolSupport v4.29-dev for 1.14.4](https://www.spigotmc.org/resources/protocolsupport.7201/)
- [ProtocolSupportStuff v2.0.0](https://www.spigotmc.org/resources/protocolsupportstuff.44527/)

![2020-02-17_18 05 35](https://user-images.githubusercontent.com/1829157/74691295-2d0ad500-51b0-11ea-9463-8979ac936cac.png)

**Comment by ErdbeerbaerLP** [comment]
Try joining older version (like 1.8)

**Comment by BenWoodworth** [comment]
I'm still seeing the same thing. Are there any other plugins that could be causing this?
![image](https://user-images.githubusercontent.com/1829157/74748670-e613f280-5236-11ea-8c75-ecd1625dc884.png)

And out of curiosity, are you able to craft a Stonecutter like this?
![image](https://user-images.githubusercontent.com/1829157/74749098-a1d52200-5237-11ea-96fd-0f0f6236bf05.png)

**Comment by ErdbeerbaerLP** [comment]
🤔 Disabled some plugins but did not change anything.
Tested around even more, This bug only happens when in creative mode and using /give to get the item. But it seems like it is not because this plugin. Inserting an "Future end crystal" (client: stone) into the crafting grid crafts an button, unless you used /give in survival mode


I might want to report to ProtocolSupport

**Comment by ErdbeerbaerLP** [comment]
Yes, ProtocolSupport itself caused this. Full update to 1.15 fixed this.
