### ISSUE TITLE
Plugin does not generate any files with no error.

### ISSUE THREAD

**Issue by PQguanfang** [BenWoodworth/FastCraft#152]
1.Download the plugin from SpigotMC
2.Put it in plugins folder
3.Reload the server
4.It says plugin have been enabled with no error
But I can not find the folder that the plugin should generate.
When I try to use the command /fastcraft,the server says the command does not exist.

Use:PaperSpigot1.15.2
FastCraft 3.0.0-beta1
![45180BCB-0116-43DB-9256-D0E5127BCAC2](https://user-images.githubusercontent.com/35395058/75606595-566d1e80-5b29-11ea-9305-1d9e6539c624.jpeg)

**Comment by BenWoodworth** [comment]
Hi! The config and commands have not been added yet in v3. You can read more about what's missing/added in the update notes:
https://www.spigotmc.org/resources/fastcraft.20544/update?update=320304
