### ISSUE TITLE
Could not pass event CraftItemEvent

### ISSUE THREAD

**Issue by DAmNRelentless** [BenWoodworth/FastCraft#153]
## Description
I know this has been reported in some issues already but these are from 2016 and are all closed or have been marked as fixed, however the bug still exists.
If you have multiple plugins installed, FastCraft triggers a lot of errors, when you craft anything with it.

## Reproduction
- have multiple plugins installed
- open the crafting table and craft any item
- see the console log

## Output/Files
- Stack Trace: https://mcpaste.io/5d6b111684344969

## Server Details
- FastCraft Version: 3.0.0-beta.3
- Server Version: Paper 121

**Comment by BenWoodworth** [comment]
Thanks for reporting! This looks like it's a new issue.

Could you try this build and let me know how it works? I think it should fix those errors.
https://634-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft.jar

**Comment by DAmNRelentless** [comment]
Not as many errors but there is still an error wit hthe CraftItemEvent
https://mcpaste.io/8c3e5ba9ebdd51cf

**Comment by BenWoodworth** [comment]
This looks like it might be a bug with UpgradableHoppers. I'll contact the dev about that for more info.

Do you know what version you're using?

**Comment by DAmNRelentless** [comment]
I reported this on his Discord already and he said I should message you about this. Maybe a bit communication between you two isn't so bad to fix this. He is very responsive.
I am using v1.2.8.9

**Comment by BenWoodworth** [comment]
I couldn't join his Discord, but I sent him a message on SpigotMC. I'll let you know when I get more info.

**Comment by BenWoodworth** [comment]
This build should fix the problem:
https://635-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft.jar

**Comment by DAmNRelentless** [comment]
Works, thanks a lot!
