### ISSUE TITLE
Not all items are available in fastcraft

### ISSUE THREAD

**Issue by ElTande** [BenWoodworth/FastCraft#158]
## Description
Hi, not all items are available in fastcraft (for exemple with a wood and a stick, it wont show up the craft for the sword, shovel, etc..)

## Reproduction
- STEP 1
- STEP 2
- ...

## Output/Files
- Stack Trace: https://gist.github.com/
- `/fcadmin debug`: https://gist.github.com/
- RELEVANT CONFIGS: https://gist.github.com/

## Server Details
- FastCraft Version: v3.0.0-beta.4
- Server Version: SPIGOT 1.8.8
- RELEVANT PLUGINS: #.#.#

**Comment by BenWoodworth** [comment]
Thanks for reporting! This build should fix it:
[FastCraft.jar](https://665-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft.jar)

Let me know if it works :)

**Comment by ElTande** [comment]
yes, it works. Thanks !

**Comment by BenWoodworth** [comment]
You're very welcome!
