### ISSUE TITLE
Request to add Essentials /craft compatibility

### ISSUE THREAD

**Issue by JeffDwyer3339** [BenWoodworth/FastCraft#164]
## Description
EssentialsX includes a /craft command which brings up a crafting interface, would it be possible to get fastcraft working on that as well as on standard crafting tables?

## Server Details
- Server: PaperSpigot 1.15.2
- FastCraft: v3.0.0

**Comment by BenWoodworth** [comment]
I'm planning on adding a `/fastcraft craft` command (#163) in the next release, and I plan on adding `/craft` as well, which can be used instead of EssentialsX's command :)
