### ISSUE TITLE
Request lang: es-LA (Latin America)

### ISSUE THREAD

**Issue by Rubenicos** [BenWoodworth/FastCraft#165]
File:
https://hasteb.in/ahuyeyoz

**Comment by BenWoodworth** [comment]
Thank you!

I changed `Crafteos Rápidos` -> `FastCraft`. Is the grammar okay here?
```
"gui.toolbar.workbench.description.1": "${aqua}Debes usar ${green}/fc toggle${aqua} para apagar o encender la FastCraft"
```

**Comment by Rubenicos** [comment]
"${aqua}Debes usar ${green}/fc toggle${aqua} para apagar o encender el FastCraft"

**Comment by BenWoodworth** [comment]
https://minecraft.gamepedia.com/Language#Removed_languages

Minecraft no usa es_LA. ¿Es esto es_AR, es_CL, es_MX, es_UY o es_VE? ¿Funciona para todos?

**Comment by Rubenicos** [comment]
Rename it with es-VE

**Comment by BenWoodworth** [comment]
Gracias! :)
https://www.spigotmc.org/resources/fastcraft.20544/updates
