### ISSUE TITLE
my bug with UTF-8 encoding

### ISSUE THREAD

**Issue by minhthanh920** [BenWoodworth/FastCraft#167]
## Server Details
- Server: paper 1.15.2
- FastCraft: v3.1.0

## Errors
![2020-05-03_14 51 39](https://user-images.githubusercontent.com/39220335/80908868-b82a4e80-8d4d-11ea-92e1-79ee0fce5f02.png)

**Comment by BenWoodworth** [comment]
For me:
![2020-05-03_06 59 17](https://user-images.githubusercontent.com/1829157/80912582-ed15b180-8d0b-11ea-8a5c-0755d53ed3da.png)
![2020-05-03_06 59 26](https://user-images.githubusercontent.com/1829157/80912585-f4d55600-8d0b-11ea-8915-fad0b7dfbb9a.png)

**Comment by BenWoodworth** [comment]
https://www.spigotmc.org/threads/fastcraft.133803/page-47#post-3789860
![upload_2020-5-3_15-15-30](https://user-images.githubusercontent.com/1829157/80912657-7a590600-8d0c-11ea-9ce1-c99dbeb97f35.png)

**Comment by BenWoodworth** [comment]
Does this fix the issue?
https://792-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft.jar

**Comment by BenWoodworth** [comment]
Should be fixed in 3.1.1 (it was fixed for someone else). Let me know if it's still an issue :)
