### ISSUE TITLE
Error with v3.2.3

### ISSUE THREAD

**Issue by SrBedrock** [BenWoodworth/FastCraft#180]
## Description

Error with org.bukkit.Material org.bukkit.Material.getCraftingRemainingItem() after commit dc7b843

## Server Details

- Server: 1.15.2
- FastCraft: v3.2.3

## Errors

https://paste.gg/p/anonymous/4f1bbe35025441afa9cc6c15425377aa/files/0371bbfd4f4c474a9124d44178db983c/raw

**Comment by BenWoodworth** [comment]
Hi! About a month ago `getCraftingRemainingItem()` was added to `Material` in Bukkit. I'm not familiar with Tuinity, but you might have to get a newer build, or have them sync up with the latest Bukkit commits

**Comment by BenWoodworth** [comment]
I just checked PaperMC and Tuinity, and it looks like they're both have the new `getCraftingRemainingItem()` change, so getting a new server build should fix this for you :)

**Comment by SrBedrock** [comment]
Understood, I will update my version.
