### ISSUE TITLE
Issue with custom items

### ISSUE THREAD

**Issue by ElBananaa** [BenWoodworth/FastCraft#183]
## Description
Hi, I recently installed your plugin on my server, and I noticed that I got an error when trying to craft custom items (with custom crafts) using the plugin. I can't craft items, and I get en error when clicking on them.

## Server Details
- Server: paper 1.12.2 (v1618à
- FastCraft: v3.2.5

The plugin used for the custom crafts is WildTools v2.8.1.

## Errors
https://pastebin.com/nP6r7Ehx

**Comment by BenWoodworth** [comment]
Thanks for reporting! What's the item you're crafting when the error happens?

**Comment by BenWoodworth** [comment]
Does this build fix it?
https://955-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft.jar

**Comment by ElBananaa** [comment]
Hi! Sorry for answering late!
Yes, it fixed the issue, thanks !

Have a nice day,
Stay safe.
