### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by WarnDangerous** [BenWoodworth/FastCraft#190]
## Description
Error into the console :
https://pastebin.com/4J5NX1Um

## Server Details
- Server: 1.12.2
- FastCraft: v3.2.9

## Errors
https://pastebin.com/4J5NX1Um

**Comment by BenWoodworth** [comment]
Hi! This should fix it:
https://1024-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft-3.2.9-5.g585716de.jar

Let me know if it's still an issue :)

**Comment by WarnDangerous** [comment]
Sorry for the delay, no errors anymore :)

**Comment by BenWoodworth** [comment]
Thanks for updating me!
