### ISSUE TITLE
BanItem compatibility

### ISSUE THREAD

**Issue by benfiratkaya** [BenWoodworth/FastCraft#194]
## Description

Can you add BanItem compatibility?
https://www.spigotmc.org/resources/banitem-1-7-1-17.67701/

**Comment by BenWoodworth** [comment]
Hi! What's it that needs to be made compatible? I'm not familiar with the plugin

**Comment by benfiratkaya** [comment]
We ban items with BanItem plugin. And when I install FastCraft I can craft banned items with FastCraft. You need disable banned crafts.

**Comment by BenWoodworth** [comment]
I think I was able to fix it. Could you give this a try?
https://1033-53271895-gh.circle-artifacts.com/0/artifacts/FastCraft-3.2.10-1.g05e36965.jar

**Comment by benfiratkaya** [comment]
it's works thanks!
