### ISSUE TITLE
how i change language ?

### ISSUE THREAD

**Issue by poyrats** [BenWoodworth/FastCraft#198]
## Description
I want change language file to Turkish

## Server Details
- Server: This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- FastCraft: v3.2.10

## Errors
No error

**Comment by BenWoodworth** [comment]
Hi! Do you mean in the game or in the server console?

In the game, FastCraft will automatically use the player's locale. So if the language is set to Turkish in Minecraft's game settings, the FastCraft GUI should also be in Turkish

**Comment by poyrats** [comment]
oh thanks.
