### ISSUE TITLE
Request: Flag to bypass custom LORE values

### ISSUE THREAD

**Issue by Drag0nz69** [BenWoodworth/FastCraft#44]
# Description

This is not a bug but a request. Would it be possible to add a flag in custom recipes to have the recipe "Ignore" custom lores on an ingredient item?  

Here is a scenario:
    My server has custom fish. When they catch a fish it has a date and weight of the fish in the lore. This is going to be a different value for each fish. I would like to create some custom recipes for them to craft items with the various fish (Which have custom names too). The names are not an issue as they stay constant, but the lores change.

I can think of scenarios where someone might want to ignore enchants and custom names too. But not always, so flags to toggle checks on Name, Lore, and Enchants separately would be awesome.

-Dragonz

**Comment by BenWoodworth** [comment]
Custom recipes have been removed, so this issue is no longer relevant.
