### ISSUE TITLE
New 1.9 Arrows

### ISSUE THREAD

**Issue by CloudeLecaw** [BenWoodworth/FastCraft#74]
i saw that currently all new 1.9 arrows cant be shown by FastCraft+
You should add it as a new todo points :)

**Comment by CloudeLecaw** [comment]
hm still no answer? :(

**Comment by BenWoodworth** [comment]
Sorry, must have missed this... 😬
I think those recipes are disabled in the code right now because Bukkit's API makes it difficult/impossible to handle recipes like these. I'm going to be playing around with NMS to try to support recipes like the new arrows, fireworks, etc.

**Comment by CloudeLecaw** [comment]
sounds good :)
i hope that this 1.13 update does not desctroy to much Plugins. The Players love the way how your Plugin offers them crafting

**Comment by BenWoodworth** [comment]
It's still not possible to know these arrow recipes through Bukkit's API, so I won't be adding this :(
