### ISSUE TITLE
Bug: when you much ingredients its not use all.

### ISSUE THREAD

**Issue by kleinesgumi** [BenWoodworth/FastCraft#81]
look at this screenshot: http://image.prntscr.com/image/a4a935fbde8042f59377886255adcdf4.png
i want 1500x logs,300x iron_ingots and netherstars but it only takes iron_ingots :(

(it takes only the highest in the list)

**Comment by CloudeLecaw** [comment]
have u checked the corect names and Format of your file?
i see u use wrong names!
.
megaxp-flasche:
  type: shaped
  ingredients:
    p:         [1500, 'minecraft:log']
    i:  [300, 'minecraft:iron_ingot']
    n: [15, 'minecraft:nether_star']
  shape:
  - 'pin'
  - '   '
  - '   '
  result: [20, 'experience_bottle', 0, '{display:{Name:"MegaXP Flasche"}}']


this one works :)
