### ISSUE TITLE
Other plugins can't edit items through the FastCraft+ craft event

### ISSUE THREAD

**Issue by CloudeLecaw** [BenWoodworth/FastCraft#84]
<strike>Suggestion: 

Could you add an Optional Lorecreator? like: Crafted by (Player)
this would help to find the owner of an item easier.</strike>
currently crafted fastcraft items Bypass craftplugns that edit the lore on normal craftings.

**Comment by BenWoodworth** [comment]
I'm going to mark this as a bug. Other plugins should be able to modify items crafted through the FastCraft+ interface.

**Comment by CloudeLecaw** [comment]
Here is a piture so u better see what i mean :3

![image](https://cloud.githubusercontent.com/assets/12080017/20798674/f99438c8-b7df-11e6-87db-c3c1427f1a27.png)

In this setup the Plugin: Craftedby from BillyGalbreath
normal would add the words "Crafted by %playername% to each item as Lore that was crafted
in a workbench. May u see if i use the normal workbench it works fine..

im sure that this effect other plugins too that add a lore or attibutes to craftings in vanilla.

**Comment by BenWoodworth** [comment]
Just an update:
This issue will be resolved in the v1.0 release.

**Comment by BenWoodworth** [comment]
Should be fixed in 3.0
