### ISSUE TITLE
Suggestion shift+click for bulk

### ISSUE THREAD

**Issue by Joapple** [BenWoodworth/FastCraft#85]
We use your plugin and it's awesome, but a feature got requested by our community. When using shift+click on the normal crafting grid use the max that inventory let you craft, can this be implemented in fastcraft also ? Would love to see that!

Thanks keep up the good work!

Joapple

**Comment by Rustoak** [comment]
Any update on this functionality?

**Comment by BenWoodworth** [comment]
I don't have any plans to implement this functionality. You can use the crafting multiplier (the anvil) to quickly craft a recipe many times at once, which can accomplish the same thing.
