### ISSUE TITLE
Plugin Incompatibility: Disease and Thirsty

### ISSUE THREAD

**Issue by MackleyMag** [BenWoodworth/FastCraft#92]
# Description
The first releases was compatible with the plugins Disease and Thirsty. Now, the FastCraft is not doing the medicines craft. I think there is an intern error, because before, when it was jus FastCraft, it does well the recipes, in FastCraft+ not do anymore.

# Debug Output
<details><summary>Show **/fcadmin debug** output</summary><pre><code>
{In your server console, run the command "fcadmin debug", and put the output here}
</code></pre></details>

# Stack Trace
<details><summary>Show stack trace</summary><pre><code>
{If there's a stack trace, copy it here. Otherwise, this section can be deleted}
</code></pre></details>

**Comment by BenWoodworth** [comment]
Hi. Thanks for reporting the issue.

Could you link me to the plugins that you're having issues with?
And are there any errors in the console?

I'll take a look at this later when I have a chance.

**Comment by MackleyMag** [comment]
No error on console, just the craft don't work for those plugins anymore.

**Comment by MackleyMag** [comment]
My players have to go on manual craft for the craft if this plugins

**Comment by MackleyMag** [comment]
The links are:
https://www.spigotmc.org/resources/disease.3911/
https://dev.bukkit.org/bukkit-plugins/byte-thirst/

**Comment by BenWoodworth** [comment]
Is this still an issue in v3.0?
