### ISSUE TITLE
This overrides my other plugin

### ISSUE THREAD

**Issue by arreyazat** [BenWoodworth/FastCraft#96]
## Description
In short, I have another plugin that uses the /craft command which gives users a virtual crafting table, I noticed that even though they have the perms to use the command, this plugin overrides and says that it needs fastcraft perms to use this plugin. Can this get addressed?

**Comment by Jikoo** [comment]
Add an alias to your [commands.yml](http://wiki.bukkit.org/Commands.yml):
```yaml
aliases:
  craft:
  - myotherplugin:craft $1-
```
Aliases added this way override existing commands.

**Comment by arreyazat** [comment]
Doesn't seem to work.

My other plugin is 'VirtualPack'
are you able to please give me the exact text to copy / paste so that these plugins don't override?
Thank you.

**Comment by Jikoo** [comment]
The aliases section should already exist - CB always creates 'icanhasbukkit' as an alias for 'version' if not present. Simply add the following, ensuring that spacing matches:
```yaml
    craft:
    - virtualpack:craft $1-
```
A restart is required for changes to take effect.

**Comment by arreyazat** [comment]
Hi
I've literally copied / paste your command, restarted, saved etc.
but to no avail. The same error comes up.

**Comment by BenWoodworth** [comment]
See if this helps you resolve the issue:
https://github.com/BenWoodworth/FastCraft/wiki/Command-Conflicts

**Comment by Jikoo** [comment]
Commands registered are all lowercase, so no, capitalizing the plugin name won't help unfortunately. It could be useful to see what the existing commands.yml looks like now if the wiki page is not enough help.
